### ISSUE TITLE
Authorization 

### ISSUE THREAD

**Issue by vlad-tokarev** [odahu/odahu#28]
### Client's authentication
- [x] [Operator authentication](https://github.com/odahu/odahu-flow/issues/113)
- [x] [Airflow authentication](https://github.com/odahu/odahu-airflow-plugin/issues/9)
- [x] [Jupyterlab authentication](https://github.com/odahu/odahu-flow-jupyterlab-plugin/issues/19)
- [x] [Python SDK and odahuflowctl Client credentials flow authentication](https://github.com/odahu/odahu-flow/issues/131)

### Features
- [x] [PDP & PEP – authorization core functionality](https://github.com/odahu/odahu-flow/issues/112)
- [ ] [Audit logs](https://github.com/odahu/odahu/issues/25)
### Improvements and fixes
- [ ] Use remote JWKS to validate JWT signature
- [ ] Stress testing of Odahu API to identify bottlenecks of api+envoy
### Documentation
- [x] [Security documentation](https://github.com/odahu/odahu-docs/issues/42)
- [x] [Keycloak realm setup](https://github.com/odahu/odahu-docs/issues/49)
