### ISSUE TITLE
ODAHU docs 1.2 update

### ISSUE THREAD

**Issue by mcdoker18** [odahu/odahu#34]
Tasks:
* [ ] [Landing page](https://github.com/odahu/odahu/issues/31)
* [ ] [Update docs from presentation](https://github.com/odahu/odahu-docs/issues/60)
* [ ] [Readme improvements](https://github.com/odahu/odahu/issues/20)
* [ ] [Cluster consumption](https://github.com/odahu/odahu-docs/issues/34)
* [ ] [Describe mlflow remote training process](https://github.com/odahu/odahu-docs/issues/48)
* [ ] [Video tutorial](https://github.com/odahu/odahu/issues/16)
* [ ] [Competitor analayze](https://github.com/odahu/odahu-docs/issues/32)
